[package]
name = "back_analysis2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.74"
clap = { version = "4.3.21", features = ["derive"] }
tokyodoves = "0.1.7"
